name             'cb-base'
maintainer       'EZ Bardeguez'
maintainer_email 'ez.bardeguez@gmail.com'
license          'All rights reserved'
description      'Installs/Configures base cookbook'
version          '1.0.1'

depends 'ntp'
depends 'sudo'
depends 'poise-python'
depends 'yum'
depends 'user'
depends 'logrotate'
depends 'omnibus'
depends 'chef-client'
depends 'yum-epel'
