name             'cb-base'
maintainer       'SMN DevOps'
maintainer_email 'administrator@smndevops.com'
license          'All rights reserved'
description      'Installs/Configures base'
version          '1.0.1'

depends 'ntp'
depends 'sudo'
depends 'poise-python'
depends 'yum'
depends 'user'
depends 'logrotate'
depends 'omnibus'
depends 'chef-client'
depends 'yum-epel'
